version: '3'
services:
  nextjs:
    container_name: bcc_front
    build: ./
    networks:
      - front
  nginx:
    image: nginx:1.21.1
    container_name: bcc_front_nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nextjs
    networks:
      - front
      - nginx-proxy
    environment:
      VIRTUAL_HOST: bcc.anapolis.ifg.edu.br
      VIRTUAL_PORT: 8102
      LETSENCRYPT_HOST: bcc.anapolis.ifg.edu.br

networks:
  front:
    driver: bridge
  nginx-proxy:
    external: true

